{{- $config := fromYaml (include "imagescan.armon.config" .) -}}
{{- if and $config.featureConfig.enabled $config.agentConfig.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
rules:
- apiGroups: [""]
  resources: [ "pods", "nodes"]
  verbs: [ "list", "get" ]

- apiGroups: ["apps"]
  resources: [ "daemonsets", "deployments", "replicasets", "statefulsets"]
  verbs: [ "list", "get" ]

- apiGroups: [ "batch" ]
  resources: [ "jobs", "cronjobs" ]
  verbs: [ "list", "get" ]
{{- end -}}
