{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "workloads-security.serviceAccountName" . }}
  labels:
{{ include "workloads-security.labels" . | nindent 4 }}
{{- end -}}
