{{- define "imagescan.engine.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "imagescan.engineAndList.commonResource.name" .config }}
  namespace: {{ .config.Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" .config | indent 4 }}
data:
  {{ include "imagescan.engineAndList.commonFull.name" .config }}.crt: |
{{ .crt | b64dec | indent 4 }}
{{- end -}}