{{- define "imagescan.engine.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "imagescan.engineAndList.commonResource.name" .config }}
  namespace: {{ .config.Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" .config | indent 4 }}
type: Opaque
data:
  {{ include "imagescan.engineAndList.commonFull.name" .config }}.key: {{ .key }}
{{- end -}}