{{- define "metrics-output.secret" -}}
{{ if .config.featureConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "agent.resource.name" .config }}-fluentbit-metrics-output
  namespace: {{ .config.Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" .config | indent 4 }}
type: Opaque
data:
  metric-output.conf: |
{{ $params := dict "agentVersion" .config.agentConfig.tag "credentials" .config.Values.credentials "inputTag" "metrics" "uriParameterName" "${CP_KUBERNETES_METRIC_URI}" "retryLimit" "3"}}
{{- include "fluentbit-metrics-output.conf" $params | b64enc | indent 4 }}
{{- end -}}
{{- end -}}