{{- $config := fromYaml (include "inventory.agent.config" .) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name.prefix" $config }}-cp-cloudguard-configmap
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
data:
  clusterID: {{ required "CloudGuard Cluster ID is required" $config.Values.clusterID | quote }}