{{- $config := fromYaml (include "inventory.agent.config" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cp-cloudguard-creds
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
type: Opaque
data:
  secret: {{ required "CloudGuard API Secret is required" .Values.credentials.secret | b64enc | quote }}
  username: {{ required "CloudGuard API Key is required" .Values.credentials.user | b64enc | quote }}