{{- $config := fromYaml (include "inventory.agent.config" .) -}}
{{- if $config.Values.imageRegistry.authEnabled -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "name.prefix" $config }}-regcred
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ template "dockerconfigjson.b64enc" $config }}
{{- end -}}