{{- if .Values.imageRegistry.authEnabled -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Release.Name }}-regcred
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ template "dockerconfigjson.b64enc" . }}
{{- end -}}