{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "cp-resource-management.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "cp-resource-management.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
rules:
  - apiGroups: [""]
    resources: [ "pods", "services", "nodes", "nodes/proxy", "serviceaccounts", "namespaces" ]
    verbs: [ "list", "get" ]

  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "networkpolicies" ]
    verbs: [ "list", "get" ]

  - apiGroups: [ "extensions" ]
    resources: [ "ingresses" ]
    verbs: [ "list", "get" ]

  - apiGroups: [ "policy, extensions"]
    resources: [ "podsecuritypolicies" ]
    verbs:
    - list 
    - get

  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "roles", "rolebindings", "clusterroles", "clusterrolebindings" ]
    verbs: [ "list", "get" ]
{{ end }}
