{{ if .Values.rbac.pspEnable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "cp-resource-management.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "cp-resource-management.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "cp-resource-management.fullname" . }}
subjects:
- kind: ServiceAccount
{{ if .Values.serviceAccount.create }}
  name: {{ template "cp-resource-management.serviceAccountName" . }}
{{ else }}
  name: {{ .Values.serviceAccount.Name | quote }}
{{ end }}
  namespace: {{ .Release.Namespace }}
{{ end }}