{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "cp-resource-management.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "cp-resource-management.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups: ["", "networking.k8s.io", "policy", "extensions", "rbac.authorization.k8s.io"]
    resources:
      - pods
      - services
      - nodes
      - nodes/proxy
      - networkpolicies
      - ingresses
      - podsecuritypolicies
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
      - serviceaccounts
      - namespaces
    verbs: ["list","get"]
{{ end }}
