apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.name }}
  labels:
    app.kubernetes.io/name: {{ template "cp-resource-management.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  secret: {{ required "Please set the Dome9 API Secret" .Values.credentials.secret | b64enc | quote }}
  username: {{ required "Please set the Dome9 API key" .Values.credentials.user | b64enc | quote }}