apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cp-cloudguard-creds
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "cp-resource-management.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
type: Opaque
data:
  secret: {{ required "CloudGaurd API Secret is reqruied" .Values.credentials.secret | b64enc | quote }}
  username: {{ required "CloudGaurd API Key is required".Values.credentials.user | b64enc | quote }}