{{ if .Values.credentials.user }}
{{ if .Values.credentials.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cp-cloudguard-creds
  annotations:
    "helm.sh/hook": "pre-install"
  labels:
    app.kubernetes.io/name: {{ template "cp-resource-management.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
type: Opaque
data:
  secret: {{ .Values.credentials.secret | b64enc | quote }}
  username: {{ .Values.credentials.user | b64enc | quote }}
{{ end }}
{{ end }}