{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cp-resource-management.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "cp-resource-management.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
{{ end }}
