{{- $config := fromYaml (include "imagescan.list.config" .) -}}
{{- if $config.featureConfig.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: {{ .Release.Namespace }}
  annotations:
    agentVersion: {{ $config.agentConfig.tag }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
    imagescan-agent-type: list
spec:
  selector:
    matchLabels:
{{ include "common.labels" $config | indent 6 }}
      imagescan-agent-type: list
  replicas: 1
  template:
    metadata:
      annotations:
{{ include "common.pod.annotations" $config | indent 8 }}
        # adding it so workload will be restarted to be updated with certificates that were re-generated
        timestamp: {{ now | quote }}
      labels:
{{ include "common.labels" $config | indent 8 }}
        imagescan-agent-type: list
    spec:
{{ include "common.pod.properties" $config | indent 6 }}
      containers:
      # Main container
      - name: {{ $config.agentName }}
        image: {{ template "agent.main.image" $config }}
        imagePullPolicy: {{ $config.Values.imagePullPolicy }}
{{- if $config.agentConfig.resources }}
        resources:
{{ toYaml $config.agentConfig.resources | indent 10 }}
{{- end }}
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
        - name: servercert-volume
          mountPath: /etc/servercert
        - name: clientcert-volume
          mountPath: /etc/clientcert
        - name: clientkey-volume
          mountPath: /etc/clientkey
        command: ["/central_agent"]
        env:
        - name: REGISTRY_AGENT_MODE
          value: "list"
        - name: NODE_AGENT_SELECTOR
          value: app.kubernetes.io/name={{ template "imagescan.daemon.resource.name" . }}
          {{- /* TODO: investigate why $config instead of "." fails */}}
        - name: RELEASE_NAME
          value: {{ .Release.Name }}
        - name: CLOUDGUARD_REGION
          value: {{ include "dome9.subdomain" $config | default "us" }}
{{- /* TODO: move user env. variables to the end for all agents */}}
{{ include "common.env" $config | indent 8 }}
      volumes:
      - name: secret-volume
        secret:
          secretName: {{ .Release.Name }}-cp-cloudguard-creds
      - name: servercert-volume
        configMap:
          name: {{ template "imagescan.daemon.resource.name" . }}
          {{- /* TODO: investigate why $config instead of "." fails */}}
      - name: clientcert-volume
        configMap:
          name: {{ template "imagescan.engineAndList.commonResource.name" $config }}
      - name: clientkey-volume
        secret:
          secretName: {{ template "imagescan.engineAndList.commonResource.name" $config }}
{{- end -}}