{{- $config := fromYaml (include "admission.policy.config" .) -}}
{{ if $config.featureConfig.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "agent.service.account.name" $config }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "agent.resource.name" $config }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}