{{- $config := fromYaml (include "flowlogs.daemon.config" .) -}}
{{- if $config.featureConfig.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: {{ .Release.Namespace }}
  annotations:
    agentVersion: {{ $config.agentConfig.tag }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "common.labels" $config | indent 6 }}
  template:
    metadata:
      annotations:
{{ include "common.pod.annotations" $config | indent 8 }}
      labels:
{{ include "common.labels" $config | indent 8 }}
    spec:
{{ include "common.pod.properties" $config | indent 6 }}
      hostNetwork: true
      containers:
#fluentbit container
{{ include "telemetry.container" $config | indent 6 }}
      # Main container
      - name: {{ $config.agentName }}
        image: {{ template "agent.main.image" $config }}
        imagePullPolicy: {{ $config.Values.imagePullPolicy }}
        securityContext:
{{- if eq (include "get.platform" $config) "openshift" }}
          privileged: true
{{- else }}
          runAsUser: 0
          capabilities:
            add: [ "SYS_ADMIN", "SYS_RESOURCE", "NET_ADMIN" ]
{{- end }}
        volumeMounts:
        - mountPath: /etc/secret-volume
          name: secret-volume
        - mountPath: /etc/cpconfig
          name: config-volume
        - name: metrics
          mountPath: /metric
        - name: metrics-tail
          mountPath: /metric-tail          
        command: ["/flow_logs_user"]
{{- if $config.agentConfig.resources }}
        resources:
{{ toYaml $config.agentConfig.resources | indent 10 }}
        {{- end }}
        env:
        - name: CP_FLOW_LOGS_REPORT_PERIOD
          value: {{ $config.agentConfig.flowlogsReportPeriod | quote }}
{{ include "common.env" $config | indent 8 }}
      volumes:
      - name: secret-volume
        secret:
          secretName: {{ .Release.Name }}-cp-cloudguard-creds
      - name: config-volume
        configMap:
          name: {{ template "agent.resource.name" $config }}
{{ include "fluentbit-metrics.volumes" $config | indent 6 }}
{{ end }}
