{{ if .Values.rbac.pspEnable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-image-uploader
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ .Release.Name }}-image-uploader
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-image-uploader
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-image-uploader
    namespace: {{ .Release.Namespace }}
{{ end }}