{{- define "gsl-enforcer-secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "agent.resource.name" .config }}
  namespace: {{ .config.Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" .config | indent 4 }}
type: Opaque
data:
  cert.pem: {{ .tls.crt }}
  key.pem: {{ .tls.key }}
{{- end -}}