{{- $config := fromYaml (include "admission.enforcer.config" .) -}}
{{ if $config.featureConfig.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
rules: 
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - clusterrolebindings
  verbs:
  - get 
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
{{ end }}