{{- $config := fromYaml (include "admission.enforcer.config" .) -}}
{{ if $config.featureConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "agent.resource.name" $config }}-fluentbit
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush       5
        Daemon      Off
        Log_Level   info
    [INPUT]
        Name             tail
        Path             admission/alerts/alerts.log
        Tag              ac-alert

    [OUTPUT]
        Name             http
        Match            ac-alert
        Format           json_stream
        Host             ${CP_KUBERNETES_DOME9_URL}
        Uri              ${CP_KUBERNETES_ADMISSION_CONTROLLER_ALERTS_URI}
        Port             443  
        Compress         gzip
        tls              On
        tls.verify       On
        tls.debug        0
        http_User        ${CP_KUBERNETES_USER}
        http_Passwd      ${CP_KUBERNETES_PASS}
        Header           Kubernetes-Account  ${CP_KUBERNETES_CLUSTER_ID}
        
{{ $params := dict "metricPath" "/metric" "agentVersion" $config.agentConfig.tag }}
{{ include "fluentbit-metric.conf" $params | indent 4 }}

{{- end -}}