{{- $config := fromYaml (include "admission.enforcer.config" .) -}}
{{ if $config.featureConfig.enabled }}
{{ $params := dict "metricPath" "/metric" "agentVersion" $config.agentConfig.tag "metricTailPath" "/metric-tail/*/*" }}
{{ template "telemetry.configmap" dict "config" $config }}

    [INPUT]
        Name             tail
        Path             admission/alerts/alerts.log
        Tag              ac-alert
        storage.type     filesystem
        Mem_Buf_Limit    1mb

    [OUTPUT]
        Match                       ac-alert
        Uri                         ${CP_KUBERNETES_ADMISSION_CONTROLLER_ALERTS_URI}
        storage.total_limit_size    100M
        Retry_Limit                 False         
{{ include "fluentbit-http-output-param.conf" $params | indent 8 }}
        

{{- end -}}