{{- $config := fromYaml (include "admission.enforcer.config" .) -}}
{{ if $config.featureConfig.enabled }}
{{ $params := dict "metricPath" "/metric" "metricTailPath" "/metric-tail/*/*" }}
{{ template "telemetry.configmap" dict "config" $config }}

    [INPUT]
        Name             tail
        Path             admission/alerts/alerts.log
        Tag              ac-alert
        storage.type     filesystem
        Mem_Buf_Limit    1mb
        Buffer_Max_Size  1mb
        Skip_Long_Lines  true

    [INPUT]
        Name             tail
        Path             admission/reviews/reviews.log
        Tag              ac-reviews
        storage.type     filesystem
        Mem_Buf_Limit    1mb

    @INCLUDE alert-output.conf
    @INCLUDE review-output.conf    

{{- end -}}