{{- $config := fromYaml (include "admission.enforcer.config" .) -}}
{{- if $config.featureConfig.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "agent.resource.name" $config }}-fluentbit-review-output
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
type: Opaque
data:
  review-output.conf: |-
{{ $params := dict "agentVersion" $config.agentConfig.tag "credentials" $config.Values.credentials "inputTag" "ac-reviews" "uriParameterName" "${CP_KUBERNETES_ADMISSION_CONTROLLER_REVIEWS_URI}" "retryLimit" "False" }}
{{- include "fluentbit-http-output-param.conf" $params | b64enc | indent 4 }}
{{- end -}}
