{{ if .Values.addons.imageUploader.enabled }}
{{ if .Values.rbac.pdpEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-gsl-enforcer-role
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ .Release.Name }}-gsl-enforcer-role
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
rules:
rules:
  - apiGroups: 
      - rbac.authorization.k8s.io
    resources: 
      - rolebindings 
      - clusterrolebindings
    verbs: 
      - get 
      - list
      - watch
  - apiGroups: 
      - dome9.checkpoint.com
    resources:
      - detectionrules
      - preventionrules
    verbs:
      - get
      - list
      - watch
{{ end }}
{{ end }}