{{- $config := fromYaml (include "runtime.daemon.config" .) -}}
{{- if $config.featureConfig.enabled -}}
{{- if contains "openshift" (include "get.platform" $config) }}
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: "master"
  name: 99-master-kernel-devel
spec:
  config:
    ignition:
      version: 3.1.0
  extensions:
    - kernel-devel
{{- end }}
{{- end }}
