{{- $config := fromYaml (include "runtime.daemon.config" .) -}}
{{- if $config.featureConfig.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "agent.resource.name" $config }}-alerts
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info

    [INPUT]
        Name             tail
        Path             /rp4c/alerts/alerts.log
        Tag              rp-alert

    [INPUT]
        Name             tail
        Path             /rp4c/profiling/profiling.log
        Tag              rp-profiling

    [OUTPUT]
        Name             http
        Match            rp-alert
        Format           json_lines
        Host             ${CP_KUBERNETES_DOME9_URL}
        Uri              ${CP_KUBERNETES_RUNTIME_ALERT_URI}
        Port             443  
        Compress         gzip
        tls              On
        tls.verify       On
        tls.debug        0
        http_User        ${CP_KUBERNETES_USER}
        http_Passwd      ${CP_KUBERNETES_PASS}
        Header           Kubernetes-Account     ${CP_KUBERNETES_CLUSTER_ID}
        Header           Node-Name              ${HOSTNAME}

    [OUTPUT]
        Name             http
        Match            rp-profiling
        Format           json_lines
        Host             ${CP_KUBERNETES_DOME9_URL}
        Uri              ${CP_KUBERNETES_RUNTIME_PROFILING_URI}
        Port             443
        Compress         gzip
        tls              On
        tls.verify       On
        tls.debug        0
        http_User        ${CP_KUBERNETES_USER}
        http_Passwd      ${CP_KUBERNETES_PASS}
        Header           Kubernetes-Account     ${CP_KUBERNETES_CLUSTER_ID}
        Header           Node-Name              ${HOSTNAME}

{{- end -}}
