{{- $config := fromYaml (include "runtime.daemon.config" .) -}}
{{- if $config.featureConfig.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "agent.resource.name" $config }}-fluentbit-metrics
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
data:
  fluent-bit.conf: |-

{{ $params := dict "metricPath" "/rp4c/metric" "metricTailPath" "/rp4c/metric/*" }}
{{ include "fluentbit-metric.conf" $params | indent 4 }}

    [INPUT]
        Name                        tail
        Path                        /rp4c/alerts/alerts.log
        Tag                         rp-alert
        storage.type                filesystem
        Mem_Buf_Limit               1mb
        Buffer_Max_Size             1mb
        Skip_Long_Lines             true

    [INPUT]
        Name                        tail
        Path                        /rp4c/profiling/profiling.log
        Tag                         rp-profiling
        storage.type                filesystem
        Mem_Buf_Limit               1mb
        Buffer_Max_Size             1mb
        Skip_Long_Lines             true        
        
    [INPUT]
        Name                        tail
        Path                        /rp4c/telemetry/telemetry.log
        Tag                         rp-telemetry
        Mem_Buf_Limit               1mb
 
    @INCLUDE alert-output.conf
    @INCLUDE profile-output.conf
    @INCLUDE telemetry-output.conf

{{- end -}}