{{- $config := fromYaml (include "runtime.daemon.config" .) -}}
{{- if $config.featureConfig.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "agent.resource.name" $config }}-fluentbit-metrics
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
data:
  fluent-bit.conf: |-

{{ $params := dict "metricPath" "/rp4c/metric" "agentVersion" $config.agentConfig.tag "metricTailPath" "/rp4c/metric/*" }}
{{ include "fluentbit-metric.conf" $params | indent 4 }}

    [INPUT]
        Name                        tail
        Path                        /rp4c/alerts/alerts.log
        Tag                         rp-alert
        storage.type                filesystem
        Mem_Buf_Limit               1mb


    [INPUT]
        Name                        tail
        Path                        /rp4c/profiling/profiling.log
        Tag                         rp-profiling
        storage.type                filesystem
        Mem_Buf_Limit               1mb
        
    [INPUT]
        Name                        tail
        Path                        /rp4c/telemetry/telemetry.log
        Tag                         rp-telemetry
        Mem_Buf_Limit               1mb
        
    [OUTPUT]
        Match                       rp-alert
        Uri                         ${CP_KUBERNETES_RUNTIME_ALERT_URI}
        storage.total_limit_size    100M
        Retry_Limit                 False        
{{ include "fluentbit-http-output-param.conf" $config | indent 8 }}

    [OUTPUT]
        Match                       rp-profiling
        Uri                         ${CP_KUBERNETES_RUNTIME_PROFILING_URI}
        storage.total_limit_size    100M  
        Retry_Limit                 False
{{ include "fluentbit-http-output-param.conf" $config | indent 8 }}
        
    [OUTPUT]
        Match                       rp-telemetry
        Uri                         ${CP_KUBERNETES_RUNTIME_TELEMETRY_URI}
        Retry_Limit                 3
{{ include "fluentbit-http-output-param.conf" $config | indent 8 }}


{{- end -}}
