{{- $configs := fromYaml (include "runtime.daemon.config.multiple" .) -}}
{{- range $_, $config := $configs -}}
{{- $config = $config | fromYaml -}}
{{- /* Make ".Files" of the chart accessible and properly formatted when accessed via $config' */ -}}
{{- $_ := set $config "Files" $.Files -}}
{{- /* Mark the config as holding a resource of type "DaemonSet" */ -}}
{{- $_ := set $config "resourceKind" "DaemonSet" -}}
{{- if $config.featureConfig.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "daemonset.daemon.resource.name" $config }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "common.selector.labels" $config | indent 6 }}
{{ include "daemonset.updateStrategy" $config | indent 2}}
  template:
    metadata:
      annotations:
{{ include "common.pod.annotations" $config | indent 8 }}
{{ include "runtime.daemon.apparmor.annotation" $config | indent 8 }}    
      labels:
{{ include "common.labels.with.chart" $config | indent 8 }}
    spec:
{{ include "common.pod.properties" $config | indent 6 }}
      hostNetwork: true  # needed for DNS request listener
      {{- if or $config.featureConfig.enableFileReputation (or (eq $config.platform "kubernetes.coreos") (eq $config.platform "eks.bottlerocket")) }}
      hostPID: true
      {{- end }}
      initContainers:
      {{- if and $config.featureConfig.enableFileReputation (eq $config.containerRuntime "cri-o") }}
      # cri-o folder which contains containers root fs can be mounted privately.
      # it depends on variable skip_mount_home in /etc/containers/storage.conf [storage.options.overlay]
      # if skip_mount_home==false, private mount will be created.
      # So nested/sub mounts will not be propagated to WorkloadSecurity container.
      # The following container changes mount type to 'shared' on host in a hacky way:
      # Literally container escapes its mount's isolation by changing mount namespace
      # to 'init' process namespace, then changes the type of the required mount to 'shared'
      - name: criofsfix
        image: docker.io/library/busybox:1
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sh", "-c", "--" ]
        securityContext:
          privileged: true
          {{- if (eq $config.platform "kubernetes.coreos") }}
          runAsUser: 0
          {{- end }}
        args:
        - |
          # check that /var/lib/containers/storage/overlay is a mount point
          if [ $(nsenter --mount=/proc/1/ns/mnt -- grep -Fc ' /var/lib/containers/storage/overlay ' /proc/self/mountinfo) -gt 0 ];
          then
            nsenter --mount=/proc/1/ns/mnt -- mount --make-shared /var/lib/containers/storage/overlay;
          fi
      {{- end }}
      # probe (sysdig)
      - {{ $containerConfig := merge $config (dict "containerName" "probe") -}}
        name: {{ $containerConfig.containerName }}
        image: {{ template "agent.sidecar.image" $containerConfig }}
        imagePullPolicy: {{ $config.Values.imagePullPolicy }}
        {{- if $config.agentConfig.probe.resources }}
        resources:
{{ toYaml $config.agentConfig.probe.resources | indent 10}}
        {{- end }}
        env:
        {{- if $config.featureConfig.BPF }}
        - name: HOME
          value: "/sysdig"
        - name: SYSDIG_BPF_PROBE
          value: ""
        {{- if (eq $config.platform "kubernetes.coreos") }}
        - name: FCOS_AUTO_KERNEL_HEADERS
          value: "1"
        {{- end }}
        {{- if eq "eks" $config.platform }}
        - name: AMAZON_AUTO_KERNEL_HEADERS
          value: "1"
        {{- end }}
        {{- if contains "openshift" $config.platform }}
        - name: SYSDIG_WAIT_FOR_KERNEL_SOURCE_TIMEOUT  # given in seconds
          value: "1800"
        {{- end }}
        {{- end }}
        {{- if $config.Values.proxy }}
        - name: http_proxy
          value: "{{ $config.Values.proxy }}"
        {{- end }}
{{ include "common.env" $config | indent 8 }}
        securityContext:
        {{- if or (eq $config.platform "eks.bottlerocket") (eq $config.platform "kubernetes.coreos") }}
          privileged: true
          runAsUser: 0
        {{- else if or (not $config.featureConfig.BPF) (contains "openshift" $config.platform) }}
          privileged: true
        {{- else }}
          runAsUser: 0
        {{- end }}
        volumeMounts:
        - name: boot-vol
          mountPath: /host/boot
          readOnly: true
        - name: modules-vol
          mountPath: /host/lib/modules
          readOnly: true
        - name: usr-vol
          mountPath: /host/usr
          readOnly: true
        - name: host-etc-vol
          mountPath: /host/etc
          readOnly: true
        {{- if $config.featureConfig.BPF }}
        - name: sysdig-probe-vol
          mountPath: /sysdig
        {{- else }}
        - name: host-dev-vol
          mountPath: /host/dev
        {{- end }}
        {{- if or (eq $config.platform "kubernetes.coreos") (eq "eks" $config.platform) }}
        - name: host-root-vol
          mountPath: /host/root
        {{- end }}
      # coscompat
      {{- if or (eq "gke.cos" $config.platform) (eq "gke.autopilot" $config.platform) }}
      - {{ $containerConfig := mergeOverwrite $config (dict "containerName" "coscompat") -}}
        name: {{ $containerConfig.containerName }}
        image: {{ template "agent.sidecar.image" $containerConfig }}
        imagePullPolicy: {{ $config.Values.imagePullPolicy }}

        securityContext:
          runAsUser: 0
          capabilities:
            add:
            - AUDIT_CONTROL

        {{- if $config.agentConfig.coscompat.resources }}
        resources:
{{ toYaml $config.agentConfig.coscompat.resources | indent 10}}
        {{- end }}

        volumeMounts:
        - name: systemd
          mountPath: /etc/systemd/system
        - name: system-dbus-socket
          mountPath: /var/run/dbus/system_bus_socket
      {{- end }}
      containers:
      # Main container
      - name: {{ $config.agentName }}
        image: {{ template "agent.main.image" $config }}
        imagePullPolicy: {{ $config.Values.imagePullPolicy }}
        args:
        - run-config
        - -d
        - /etc/checkpoint/cpsba/awl_config_dome9.json
        {{- if $config.agentConfig.resources }}
        resources:
{{ toYaml $config.agentConfig.resources | indent 10 }}
        {{- end }}
        env:
        - name: LANG
          value: C.UTF-8
        - name: SBA_TELEMETRY_SAVE_TO_FILE
          value: "1"
        - name: SBA_CONTAINER_RUNTIME
          value: {{ $config.containerRuntime }}
        - name: SBA_USE_DOME9_FORWARDER
          value: "1"
        - name: SBA_FORWARDER_AGENT_VERSION
          value: {{ $config.agentConfig.tag | quote }}
        - name: TELEMETRY_VERSION
          value: {{ $config.Values.telemetryVersion }}
        - name: CP_KUBERNETES_DOME9_URL
          value: {{ template "cloudguardURL_host" $config }}
        - name: CP_KUBERNETES_RUNTIME_ALERT_URI
          value: {{ template "cloudguardURL_path" $config }}runtimeevent/alert
        - name: CP_KUBERNETES_RUNTIME_PROFILING_URI
          value: {{ template "cloudguardURL_path" $config }}runtimeevent/profiling
        - name: CP_KUBERNETES_METRIC_URI
          value: {{ template "cloudguardURL_path" $config }}agenttelemetry
        - name: CP_KUBERNETES_RUNTIME_TELEMETRY_URI
          value: {{ template "cloudguardURL_path" $config }}runtimetelemetry        
        - name: POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        {{- if $config.featureConfig.BPF }}
        - name: SYSDIG_BPF_PROBE
          value: "/sysdig/.scap/scap-bpf.o"
        {{- end }}
        - name: SBA_USE_NETFILTER_QUEUE
          value: "1"
      {{- if not $config.featureConfig.enableFileReputation }}
        - name: SBA_REQUIRED_BLADES
          value: "SBA,BG"
      {{- end }}
{{ include "common.env" $config | indent 8 }}
        securityContext:
        {{- if or (not $config.featureConfig.BPF) (contains "openshift" $config.platform) }}
          privileged: true
        {{- else if (eq $config.platform "kubernetes.coreos") }}
          privileged: true
          runAsUser: 0
        {{- else }}
          runAsUser: 0
          {{- if and ($config.featureConfig.enableFileReputation) (eq $config.platform "eks.bottlerocket") }}
          seLinuxOptions:
            user: system_u
            role: system_r
            type: control_t
            level: s0
          {{- end }}
          capabilities:
            add:
            - SYS_RESOURCE
            - SYS_ADMIN
            - SYS_NICE
            - SYS_PTRACE
            - FOWNER
            - SYS_PACCT
            - NET_ADMIN
            - NET_RAW
          {{- if $config.featureConfig.enableFileReputation }}
            - AUDIT_CONTROL # for fmon
            - AUDIT_READ # for fmon
            - AUDIT_WRITE # for fmon
          {{- end }}
{{ include "runtime.daemon.apparmor.securityContext" $config | indent 10 }}
	{{- end }}
        volumeMounts:
        - name: rp4c-alerts
          mountPath: /rp4c/alerts
        - name: rp4c-profiling
          mountPath: /rp4c/profiling
        - name: rp4c-metric
          mountPath: /rp4c/metric
        - name: metrics-tail
          mountPath: /metric-tail
        - name: rp4c-telemetry
          mountPath: /rp4c/telemetry
        - name: secret-volume
          mountPath: /etc/secret-volume
        {{- if eq $config.containerRuntime "docker" }}
        - name: docker-sock
          mountPath: /var/run/docker.sock
          readOnly: true
        {{- if ne $config.platform "tanzu" }}
        - name: varlibdocker-vol
          mountPath: /var/lib/docker
          mountPropagation: HostToContainer
          readOnly: true
        {{- end }}
        {{- end }}
        {{- if eq $config.containerRuntime "containerd" }}
        - name: containerd-sock
          mountPath: /run/containerd/containerd.sock
          readOnly: true
        - mountPath: /run/containerd/io.containerd.runtime.v2.task
          name: runcontainerdfs-vol
          mountPropagation: HostToContainer
          readOnly: true
        {{- end }}
        {{- if eq $config.containerRuntime "cri-o" }}
        - name: crio-sock
          mountPath: /var/run/crio/crio.sock
          readOnly: true
        - name: criofs-vol
          mountPath: /var/lib/containers/storage
          mountPropagation: HostToContainer
          readOnly: true
        - name: criohooks-vol
          mountPath: /etc/containers/oci/hooks.d/
          readOnly: false
        {{- end }}
        - name: host-proc-vol
          mountPath: /host/proc
          readOnly: true
        {{- if $config.featureConfig.BPF }}
        - name: sysdig-probe-vol
          mountPath: /sysdig
          readOnly: true
        {{- else }}
        - name: host-dev-vol
          mountPath: /host/dev
        {{- end }}
        - name: sys-vol
          mountPath: /sys/kernel/debug/
          readOnly: true
        - name: run-xtables-lock
          mountPath: /run/xtables.lock
        - name: crashdumps-vol
          mountPath: /var/log/checkpoint/cpla/crashdumps
      volumes:
      {{- if or (eq "gke.cos" $config.platform) (eq "gke.autopilot" $config.platform) }}
      - name: system-dbus-socket
        hostPath:
          path: /var/run/dbus/system_bus_socket
          type: Socket
      - name: systemd
        hostPath:
          path: /etc/systemd/system
      {{- end }}
      - name: rp4c-alerts
        emptyDir: {}
      - name: rp4c-profiling
        emptyDir: {}
      - name: rp4c-metric
        emptyDir: {}
      - name: metrics-tail
        emptyDir: {}
      - name: rp4c-telemetry
        emptyDir: {}
      {{- if eq $config.containerRuntime "docker" }}
      - name: docker-sock
        hostPath:
      {{- if eq $config.platform "tanzu" }}
          path: /var/vcap/sys/run/docker/docker.sock
          type: Socket
      {{- else }}
          path: /var/run/docker.sock
          type: Socket
      - name: varlibdocker-vol
        hostPath:
          path: /var/lib/docker
      {{- end }}
      {{- end }}
      {{- if eq $config.containerRuntime "containerd" }}
      - name: containerd-sock
        hostPath:
          path: {{ include "containerd.sock.path" $config }}
          type: Socket
      - name: runcontainerdfs-vol
        hostPath:
          path: {{ include "containerd.runtime.v2.task" $config }}
      {{- end }}
      {{- if eq $config.containerRuntime "cri-o" }}
      - name: crio-sock
        hostPath:
          path: /var/run/crio/crio.sock
          type: Socket
      - name: criofs-vol
        hostPath:
          path: /var/lib/containers/storage
      - name: criohooks-vol
        hostPath:
          path: /etc/containers/oci/hooks.d/
      {{- end }}
      - name: boot-vol
        hostPath:
          path: /boot
      - name: modules-vol
        hostPath:
          path: /lib/modules
      - name: usr-vol
        hostPath:
          path: /usr
      - name: host-proc-vol
        hostPath:
          path: /proc
      {{- if $config.featureConfig.BPF }}
      - name: sysdig-probe-vol
        hostPath:
          path: /var/local
      {{- else }}
      - name: host-dev-vol
        hostPath:
          path: /dev
      {{- end }}
      - name: sys-vol
        hostPath:
          path: /sys/kernel/debug/
      - name: host-etc-vol
        hostPath:
          path: /etc
      - name: run-xtables-lock
        hostPath:
          path: /run/xtables.lock
      - name: crashdumps-vol
        emptyDir: 
          sizeLimit: 200Ki
      {{- if or (eq $config.platform "kubernetes.coreos") (eq "eks" $config.platform) }}
      - name: host-root-vol
        hostPath:
          path: /
      {{- end }}
      - name: secret-volume
        secret:
          secretName: {{ template "cg.creds.secret.name" $config }}
---        
{{ end }}  
{{- end -}}
