{{- $config := fromYaml (include "runtime.daemon.config" .) -}}
{{- if $config.featureConfig.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
rules:
- apiGroups: ["runtimeprotection.cloudguard.checkpoint.com"]
  resources: ["*"]
  verbs: [ "list", "watch"]
{{ if $config.Values.rbac.pspEnabled }}
- apiGroups: [ "policy" ]
  resources: [ "podsecuritypolicies" ]
  verbs: ["use"]
  resourceNames:
  - {{ template "agent.resource.name" $config }}
{{- end -}}
{{- if eq (include "get.platform" $config) "openshift" }}
- apiGroups:
  - security.openshift.io 
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints 
  verbs: 
  - use
{{- end -}}
{{- end -}}