{{- $config := fromYaml (include "runtime.daemon.config" .) -}}
{{- if $config.featureConfig.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "agent.resource.name" $config }}-sba-cve
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
data:
  cve.rl: |
    global WRITE_MASK = 2;

    global SYS_SOCKET = 41;
    global SYS_EXECVE = 59;

    global AF_PACKET = 17;
    global RAW_SOCKET = 3;

    @description
    "php_cgi_metasploit"
    CVE_2012_1823:
    {
      ("php-cgi" == event.ps.name) and
        (("-d" in event.ps.args) or
         ("-s" in event.ps.args));
    }

    @description
    "php_mailer_rce"
    CVE_2016_10033:
    {
      ("sendmail" == event.ps.name) and
        (("-o" in event.ps.args) or
         ("-X" in event.ps.args));
    }

    @disabled
    @description
    "CVE-2017-7308 & CVE-2016-8655"
    CVE_2017_7308_and_CVE_2016_8655:
    {
      (event.syscall_id == SYS_SOCKET) and
        (event.net.socket_domain == AF_PACKET) and
          (event.net.socket_type == RAW_SOCKET);
    }

    @description
    "privilege escalation attempt"
    CVE_2019_14287:
    {
      (event.syscall_id is SYS_EXECVE) and
        ("sudo" is event.ps.name) and
          ("-u#" in event.ps.args);
    }

    @description
    "privilege escalation attempt"
    CVE_2019_5736:
    {
      (event.fs.flags & WRITE_MASK) and
        (event.fs.target_path is "/proc/self/exe");
    }

    @description
    "monitor attempts to use privileged utilities"
    privileged_utilities:
    {
      (event.syscall_id is SYS_EXECVE) and
        ("sudoedit" is event.ps.name);
    }
{{- end -}}
