{{- $config := fromYaml (include "runtime.daemon.config" .) -}}
{{- if $config.featureConfig.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "agent.resource.name" $config }}-sba-malware
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}

data:
  malware.rl: |
    global WRITE_MASK = 2;

    global SYS_EXECVE = 59;
    global SYS_RENAME = 82;
    global SYS_RENAMEAT = 264;

    @description
    "Chaos"
    Chaos:
    {
      ((event.syscall_id is SYS_RENAME) or
       (event.syscall_id is SYS_RENAMEAT) or
       (event.fs.flags & WRITE_MASK)) and
         (("/usr/include/gpm2.h" is event.fs.target_path) or
          ("/etc/init.d/runlevels" is event.fs.target_path) or
          ("/usr/include/cli.h" is event.fs.target_path) or
          ("/usr/include/stabd.h" is event.fs.target_path) or
          ("/usr/sbin/smdb" is event.fs.target_path));
    }

    @description
    "Ebury"
    Ebury:
    {
      ((event.syscall_id is SYS_RENAME) or
       (event.syscall_id is SYS_RENAMEAT) or
       (event.fs.flags & WRITE_MASK)) and
         ("/etc/ssh/sshd_config" is event.fs.target_path);
    }

    @description
    "EvilGnome"
    EvilGnome:
    {
      ((event.syscall_id is SYS_RENAME) or
       (event.syscall_id is SYS_RENAMEAT) or
       (event.fs.flags & WRITE_MASK)) and
         (("makeself.sh" in event.fs.target_filename) or
          (".cache/gnome-software/gnome-shell-extensions/gnome-shell-ext" in event.fs.target_path));
    }

    @description
    "Exaramel_for_linux"
    Exaramel_for_linux:
    {
      ("/sbin/init" is event.fs.target_path) or
      ("upstart|systemd|sysvinit" in event.ps.args);
    }

    @description
    "Fysbis"
    Fysbis:
    {
      ((event.syscall_id is SYS_RENAME) or
       (event.syscall_id is SYS_RENAMEAT) or
       (event.fs.flags & WRITE_MASK)) and
         (("/usr/lib/systemd" is event.fs.target_path) or
          ("/bin/rsyncd" is event.fs.target_path) or
          ("/usr/lib/systemd/system/rsyncd.service" is event.fs.target_path) or
          ("/usr/lib/systemd/system/rsyncd.service" is event.fs.target_path) or
          ("/usr/lib/cva-ssys" is event.fs.target_path) or
          ("~/.config/autostart/dbus-inotifier.desktop" is event.fs.target_path) or
          ("~/.config/autostart/" is event.fs.target_path));
    }

    @description
    "Golang"
    Golang:
    {
      ((event.syscall_id is SYS_RENAME) or
       (event.syscall_id is SYS_RENAMEAT) or
       (event.fs.flags & WRITE_MASK)) and
         ("/etc/sysconfig/selinux" is event.fs.target_path);
    }

    @description
    "Graboid"
    Graboid:
    {
      ((event.syscall_id is SYS_RENAME) or
       (event.syscall_id is SYS_RENAMEAT) or
       (event.fs.flags & WRITE_MASK)) and
         (("/var/sbin/bash" is event.fs.target_path) or
          ("live.sh" is event.fs.target_filename) or
          ("worm.sh" is event.fs.target_filename) or
          ("cleanxmr.sh" is event.fs.target_filename) or
          ("xmr.sh" is event.fs.target_filename));
    }

    @description
    "Hidden Wasp"
    hidden_wasp:
    {
      ((event.syscall_id is SYS_RENAME) or
       (event.syscall_id is SYS_RENAMEAT) or
       (event.fs.flags & WRITE_MASK)) and
         (("/etc/rc.local" is event.fs.target_path) or
          ("/usr/bin/passwd" is event.fs.target_path) or
          ("/sbin/.ifup-local" is event.fs.target_path));
    }

    @description
    "Lilocked"
    Lilocked:
    {
      ((event.syscall_id is SYS_RENAME) or
       (event.syscall_id is SYS_RENAMEAT) or
       (event.fs.flags & WRITE_MASK)) and
         (".lilocked" in event.fs.target_filename);
    }

    @description
    "Linux Rabbit/Rabbot"
    linux_rabbit:
    {
      ((event.syscall_id is SYS_RENAME) or
       (event.syscall_id is SYS_RENAMEAT) or
       (event.fs.flags & WRITE_MASK)) and
         ((".bashrc" is event.fs.target_filename) or
          ("rc.local" is event.fs.target_filename));
    }

    @description
    "SkidMap"
    SkidMap:
    {
      ((event.syscall_id is SYS_RENAME) or
       (event.syscall_id is SYS_RENAMEAT) or
       (event.fs.flags & WRITE_MASK)) and
         (("/usr/sbin/setenforce" is event.fs.target_path) or
          ("/etc/selinux/config" is event.fs.target_path) or
          ("/root/.ssh/authorized_keys" is event.fs.target_path) or
          ("/usr/bin/kaudited" is event.fs.target_path) or
          ("pam_unix.so" is event.fs.target_filename));
    }

    @disabled
    @description
    "SpeakUp"
    SpeakUp:
    {
      "/proc/cpuinfo" is event.fs.target_path;
    }

    @description
    "Umbreon"
    Umbreon:
    {
      ((event.syscall_id is SYS_RENAME) or
       (event.syscall_id is SYS_RENAMEAT) or
       (event.fs.flags & WRITE_MASK)) and
         (("/bin/espeon-shell" is event.fs.target_path) or
          ("/bin/zypper" is event.fs.target_path) or
          ("/bin/emerge" is event.fs.target_path) or
          ("/bin/umbreon.py" is event.fs.target_path) or
          ("/bin/espeon" is event.fs.target_path) or
          ("/.umbreon-ascii" is event.fs.target_path) or
          ("/hideports" is event.fs.target_path) or
          ("/promptlog" is event.fs.target_path) or
          ("espeon" is event.fs.target_filename));
    }

    @description
    "xmrig"
    xmrig:
    {
      (event.syscall_id is SYS_EXECVE) and
        ("xmrig" is event.ps.name);
    }
{{- end -}}
