{{- $config := fromYaml (include "runtime.daemon.config" .) -}}
{{- if $config.featureConfig.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "agent.resource.name" $config }}-fluentbit-telemetry-output
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
type: Opaque
data:
  telemetry-output.conf: |-
{{ $params := dict "agentVersion" $config.agentConfig.tag "credentials" $config.Values.credentials "inputTag" "rp-telemetry" "uriParameterName" "${CP_KUBERNETES_RUNTIME_TELEMETRY_URI}" "retryLimit" "3" }}
{{- include "fluentbit-http-output-param.conf" $params | b64enc | indent 4 }}
{{- end -}}
