{{- $config := fromYaml (include "inventory.agent.config" .) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
rules:
  - apiGroups: [""]
    resources: [ "pods", "services", "nodes", "nodes/proxy", "serviceaccounts", "namespaces", "resourcequotas" ]
    verbs: [ "list", "get" ]

  - apiGroups: ["apps"]
    resources: [ "daemonsets", "deployments", "replicasets", "statefulsets"]
    verbs: [ "list", "get" ]

{{/* extensions/ingress deprecated in 1.22 and networking.k8s.io/ingress is supported only from 1.14 we support both */}}
{{- if has "networking.k8s.io/v1/Ingress" .Capabilities.APIVersions }}
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "networkpolicies", "ingresses" ]
    verbs: [ "list", "get" ]
{{- else }}
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "networkpolicies" ]
    verbs: [ "list", "get" ]

  - apiGroups: [ "extensions" ]
    resources: [ "ingresses" ]
    verbs: [ "list", "get" ]  
{{- end }}

  - apiGroups: [ "policy" ]
    resources: [ "podsecuritypolicies" ]
    verbs: [ "list", "get" ]

  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "roles", "rolebindings", "clusterroles", "clusterrolebindings" ]
    verbs: [ "list", "get" ]

  - apiGroups: [ "batch" ]
    resources: [ "cronjobs" ]
    verbs: [ "list", "get" ]
