{{- $config := fromYaml (include "inventory.agent.config" .) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "agent.resource.name" $config }}
subjects:
- kind: ServiceAccount
  name: {{ template "agent.service.account.name" $config }}
  namespace: {{ .Release.Namespace }}