{{- $config := fromYaml (include "inventory.agent.config" .) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
rules:
  - apiGroups: [""]
    resources: [ "pods", "services", "nodes", "nodes/proxy", "serviceaccounts", "namespaces", "resourcequotas"]
    verbs: [ "list", "get" ]

  - apiGroups: ["apps"]
    resources: [ "daemonsets", "deployments", "replicasets", "statefulsets"]
    verbs: [ "list", "get" ]

  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "networkpolicies", "ingresses" ]
    verbs: [ "list", "get" ]

  - apiGroups: [ "extensions" ]
    resources: [ "ingresses" ]
    verbs: [ "list", "get" ]  

  - apiGroups: [ "policy" ]
    resources: [ "podsecuritypolicies" ]
    verbs: [ "list", "get" ]

  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "roles", "rolebindings", "clusterroles", "clusterrolebindings" ]
    verbs: [ "list", "get" ]

  - apiGroups: [ "batch" ]
    resources: [ "cronjobs" ]
    verbs: [ "list", "get" ]

{{- if eq (include "is.openshift.v4" $config) "openshift"}}
  - apiGroups: [ "config.openshift.io" ]
    resources: [ "clusteroperators" ]
    resourceNames: [ "openshift-apiserver" ]
    verbs: [ "list", "get" ]

  - apiGroups: [ "operator.openshift.io" ]
    resources: [ "openshiftapiservers", "kubeapiservers" ]
    resourceNames: [ "cluster" ]
    verbs: [ "list", "get" ]
  
  - apiGroups: [ "security.openshift.io" ]
    resources: [ "securitycontextconstraints" ]
    verbs: [ "list", "get" ]
{{- end}}
