{{- $config := fromYaml (include "inventory.agent.config" .) -}}
{{- if eq "openshift" (include "get.platform" $config)}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: openshift-kube-controller-manager
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get"]
    resourceNames: [ "config" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: openshift-kube-scheduler
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get"]
    resourceNames: [ "kube-scheduler-pod" ]
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: openshift-apiserver
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get"]
    resourceNames: [ "config" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: openshift-kube-apiserver
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get"]
    resourceNames: [ "config" ]
{{- end }}