{{- $config := fromYaml (include "inventory.agent.config" .) -}}
{{- if not $config.agentConfig.serviceAccountName -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
{{- end -}}