{{- $config := fromYaml (include "runtime.policy.config" .) -}}
{{- if $config.featureConfig.enabled -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: denylists.runtimeprotection.cloudguard.checkpoint.com
spec:
  group: runtimeprotection.cloudguard.checkpoint.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            data:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: denylists
    singular: denylist
    kind: DenyList
{{- end -}}