{{- $config := fromYaml (include "runtime.policy.config" .) -}}
{{- if $config.featureConfig.enabled -}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: signaturegroups.runtimeprotection.cloudguard.checkpoint.com
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
spec:
  group: runtimeprotection.cloudguard.checkpoint.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: signaturegroups
    singular: signaturegroup
    kind: SignatureGroup
{{- end -}}