apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: allowlists.runtimeprotection.cloudguard.checkpoint.com
spec:
  group: runtimeprotection.cloudguard.checkpoint.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            data:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: allowlists
    singular: allowlist
    kind: AllowList