apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: preventionrules.admissioncontrol.cloudguard.checkpoint.com
spec:
  group: admissioncontrol.cloudguard.checkpoint.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                rulebase_id:
                  type: string
                rules:
                  type: array
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: preventionrules
    singular: preventionrule
    kind: PreventionRule