{{- define "imagescan.engine-list.serviceaccount" -}}
{{- $config := .config -}}
{{- if and $config.featureConfig.enabled (not $config.agentConfig.serviceAccountName) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: {{ .config.Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
{{- end -}}
{{- end -}}