{{- $config := fromYaml (include "admission.enforcer.config" .) -}}
{{- if $config.featureConfig.enabled -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configurations.admissioncontrol.cloudguard.checkpoint.com
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
spec:
  group: admissioncontrol.cloudguard.checkpoint.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            data:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: configurations
    singular: configuration
    kind: Configuration
{{- end -}}
