{{- $config := fromYaml (include "imagescan.daemon.config" .) -}}
{{- if $config.featureConfig.enabled -}}
{{- include "container.runtime.validate" $config -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: {{ .Release.Namespace }}
  annotations:
    agentVersion: {{ $config.agentConfig.tag }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "common.labels" $config | indent 6 }}
  template:
    metadata:
      annotations:
{{ include "common.pod.annotations" $config | indent 8 }}
        # adding it so workload will be restarted to be updated with certificates that were re-generated
        timestamp: {{ now | quote }}
      labels:
{{ include "common.labels" $config | indent 8 }}
    spec:
{{ include "common.pod.properties" $config | indent 6 }}
      containers:
{{ include "telemetry.container" $config | indent 6 }}
      # Main container
      - name: {{ $config.agentName }}
        image: {{ template "agent.main.image" $config }}
        imagePullPolicy: {{ $config.Values.imagePullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
        volumeMounts:
{{- if eq $config.Values.containerRuntime "docker" }}
        - name: docker-sock-volume
          mountPath: /var/run/docker.sock
          readOnly: true
{{- end }}
        - name: serverkey-volume
          mountPath: /etc/serverkey
        - name: servercert-volume
          mountPath: /etc/servercert
        - name: clientcert-volume
          mountPath: /etc/clientcert
        - name: metrics
          mountPath: /metric
        - name: metrics-tail
          mountPath: /metric-tail
        command: ["/node_agent"]
        ports:
        - containerPort: 8443
{{- if $config.agentConfig.resources }}
        resources:
{{ toYaml $config.agentConfig.resources | indent 10 }}
        {{- end }}
        env:
{{ include "user.defined.env" $config | indent 8 }}
{{- if eq $config.Values.containerRuntime "containerd" }}
        - name: IS_CONTAINERD
          value: "true"
{{- end }}
{{- if eq $config.Values.containerRuntime "containerd" }}
      - {{ $containerConfig := merge $config (dict "containerName" "shim") -}} 
        name: {{ $containerConfig.containerName }} 
        image: {{ template "agent.sidecar.image" $containerConfig }}
        imagePullPolicy: {{ $config.Values.imagePullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
        volumeMounts:
        - name: cri-sock-volume
          mountPath: /run/cri.sock
          readOnly: true
        - name: containerd-sock-volume
          mountPath: /run/containerd/containerd.sock
          readOnly: true
        - name: host
          mountPath: /host
          readOnly: true
        - name: ld-linux
          mountPath: /lib64/ld-linux-x86-64.so.2
          readOnly: true
        - name: metrics
          mountPath: /metric
        - name: metrics-tail
          mountPath: /metric-tail
        command: ["/server"]
{{- if $config.agentConfig.shim.resources }}
        resources:
{{ toYaml $config.agentConfig.shim.resources | indent 10 }}
        {{- end }}
        env:
{{- if $config.agentConfig.shim.env }}
{{ toYaml $config.agentConfig.shim.env | indent 8 }}
{{- end -}}
{{- end }}
      volumes:
{{- if eq $config.Values.containerRuntime "docker" }}
      - name: docker-sock-volume
        hostPath:
          path: /var/run/docker.sock
          type: Socket
{{- else }}
      - name: cri-sock-volume
        hostPath:
          path: /run/containerd/containerd.sock
          type: Socket
      - name: containerd-sock-volume
        hostPath:
          path: /run/containerd/containerd.sock
          type: Socket
      - name: host
        hostPath:
          path: /
          type: Directory
      - name: ld-linux
        hostPath:
          path: /lib64/ld-linux-x86-64.so.2
          type: File
{{- end }}
      - name: serverkey-volume
        secret:
          secretName: {{ template "agent.resource.name" $config }}
      - name: servercert-volume
        configMap:
          name: {{ template "agent.resource.name" $config }}
      - name: clientcert-volume
        configMap:
          name: {{ template "imagescan.engine.resource.name" . }}
          {{/* TODO: investigate why $config instead of "." fails */}}

      - name: config-volume-fluentbit
        configMap:
          name: {{ template "agent.resource.name" $config }}-metrics
      - name: metrics
        emptyDir: {}
      - name: metrics-tail
        emptyDir: {}
{{- end -}}  