{{- $config := fromYaml (include "imagescan.daemon.config" .) -}}
{{- if $config.featureConfig.enabled -}}
{{- if $config.Values.rbac.pspEnabled -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: {{ $config.Values.podAnnotations.seccomp }}
spec:
  privileged: false
  # Required to prevent escalations to root.
  allowPrivilegeEscalation: false
  allowedHostPaths:
{{- if eq $config.containerRuntime "docker" }}
{{- if eq (include "get.platform" $config) "tanzu" }}
  - pathPrefix: /var/vcap/sys/run/docker/docker.sock
{{- else }}
  - pathPrefix: /var/run/docker.sock
{{- end }}
    readOnly: true
{{- end }}
{{- if eq $config.containerRuntime "containerd" }}
  - pathPrefix: /run/containerd/containerd.sock
    readOnly: true
{{- end }}
{{- if eq $config.containerRuntime "cri-o" }}
  - pathPrefix: /run/crio/crio.sock
    readOnly: true
  - pathPrefix: /etc/containers
    readOnly: true
  - pathPrefix: /run/containers
    readOnly: false
  - pathPrefix: /var/lib/containers
    readOnly: false
  - pathPrefix: /lib64
    readOnly: true
  - pathPrefix: /usr/bin/podman
    readOnly: true
  - pathPrefix: /usr/bin/conmon
    readOnly: true
  - pathPrefix: /usr/bin/runc
    readOnly: true
  - pathPrefix: /usr/bin/nsenter
    readOnly: true
{{- if ne (include "get.platform" $config) "openshift" }}
  - pathPrefix: /lib/x86_64-linux-gnu
    readOnly: true
  - pathPrefix: /usr/lib/x86_64-linux-gnu
    readOnly: true
{{- end }}
{{- end }}
  allowedCapabilities:
  - 'NET_BIND_SERVICE'
  volumes:
  - 'hostPath'
  - 'secret'
  - 'configMap' 
  - 'emptyDir'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
    # Forbid adding the root group.
    - min: 1
      max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
    - min: 1
      max: 65535
  readOnlyRootFilesystem: false
{{- end -}}
{{- end -}}
