{{- $config := fromYaml (include "imagescan.daemon.config" .) -}}
{{- if $config.featureConfig.enabled -}}
{{- if or $config.Values.rbac.pspEnabled (contains "openshift" $config.platform) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
rules:
{{- if $config.Values.rbac.pspEnabled }}
- apiGroups: [ "policy" ]
  resources: [ "podsecuritypolicies" ]
  verbs: [ "use"]
  resourceNames: 
  - {{ template "agent.resource.name" $config }}
{{- end }}
{{- if contains "openshift" $config.platform }}
- apiGroups:
  - security.openshift.io 
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints 
  verbs: 
  - use
{{- end -}}
{{- end -}}
{{- end -}}