{{- $config := fromYaml (include "imagescan.daemon.config" .) -}}
{{- if $config.featureConfig.enabled -}}
{{- if .Values.rbac.pspEnabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "agent.resource.name" $config }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels.with.chart" $config | indent 4 }}
rules:
- apiGroups: [ "policy" ]
  resources: [ "podsecuritypolicies" ]
  verbs: [ "use"]
  resourceNames: 
  - {{ template "agent.resource.name" $config }}
{{- end -}}
{{- end -}}